name: Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - pyproject.toml
      - docs.yml

  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.1

      - name: Install Poetry
        run: pipx install poetry==1.4.2

      - name: Install Dependencies
        run: poetry install --only docs && icl install
        env:
          POETRY_VIRTUALENVS_CREATE: false
          POETRY_REPOSITORIES_MATERIAL_INSIDERS: https://github.com/squidfunk/mkdocs-material-insiders
          POETRY_REPOSITORIES_MATERIAL_INSIDERS_USERNAME: celsiusnarhwal
          POETRY_REPOSITORIES_MATERAIL_INSIDERS_PASSWORD: ${{ secrets.GH_PAT }}

      - name: Build Documentation
        run: mkdocs build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site

  deploy:
    name: Deploy Documentation
    environment: main
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site

      - name: Deploy to Vercel
        run: npx vercel --yes --cwd site --token ${{ secrets.VERCEL_TOKEN }} ${{ github.ref_name == 'main' && '--prod' || '' }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
