name: Publish

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  publish:
    name: Publish to PyPI
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.5.x
          enable-cache: true

      - name: Bulid Package
        run: uv build --no-sources

      - name: Publish Package
        run: uv publish